# Generated by Django 5.1.6 on 2025-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=20)),
                ('course_type', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
                ('instructor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=5)),
                ('pre_enrollment_count', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('enrolled_count', models.IntegerField()),
            ],
            options={
                'db_table': 'course_offering',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=5)),
                ('day', models.CharField(max_length=10)),
                ('times', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('term', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'semester',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_year', models.IntegerField()),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'time_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTableDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=5)),
                ('schedule_info', models.CharField(max_length=255)),
                ('user_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_table_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=5)),
                ('grade', models.CharField(max_length=2)),
                ('credit_taken', models.IntegerField()),
            ],
            options={
                'db_table': 'transcript',
                'managed': False,
            },
        ),
    ]
