# Generated by Django 5.1.6 on 2025-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_level', models.IntegerField(default=0)),
                ('version_year', models.IntegerField()),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Colleges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
                ('target_year', models.CharField(max_length=10)),
                ('grade_type', models.CharField(max_length=50)),
                ('foreign_course', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor_name', models.CharField(max_length=255)),
                ('lecture_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lecture_times', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lab_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lab_times', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pre_enrollment_count', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('enrolled_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10)),
                ('times', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'COURSE_SCHEDULES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('maximum_value', models.IntegerField(default=0)),
                ('minimum_value', models.IntegerField(default=0)),
                ('applicable_year', models.IntegerField()),
            ],
            options={
                'db_table': 'GraduationRequirements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Major',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('term', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_registration_start', models.DateField()),
                ('course_registration_end', models.DateField()),
            ],
            options={
                'db_table': 'SEMESTER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_user_id', models.IntegerField()),
                ('admission_year', models.IntegerField()),
                ('completed_semester', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TIME_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTableDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_info', models.CharField(max_length=255)),
                ('user_note', models.TextField(blank=True, null=True)),
                ('custom_color', models.CharField(default='#FFFFFF', max_length=50)),
            ],
            options={
                'db_table': 'TIME_TABLE_DETAIL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(default='NA', max_length=2)),
                ('retake_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Transcript',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Universities',
                'managed': False,
            },
        ),
    ]
