# Generated by Django 5.1.6 on 2025-04-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('major_credits', models.IntegerField()),
                ('general_credits', models.IntegerField()),
                ('free_credits', models.IntegerField()),
                ('total_requirement', models.IntegerField(blank=True, null=True)),
                ('free_requirement', models.IntegerField(blank=True, null=True)),
                ('major_required_credits', models.IntegerField(default=0)),
                ('major_elective_credits', models.IntegerField(default=0)),
                ('major_required_requirement', models.IntegerField(blank=True, null=True)),
                ('major_elective_requirement', models.IntegerField(blank=True, null=True)),
                ('missing_major_subjects', models.TextField(blank=True)),
                ('missing_general_sub', models.TextField(blank=True)),
                ('major_requirement', models.TextField(blank=True)),
                ('general_requirement', models.TextField(blank=True)),
                ('detailed_credits', models.TextField(blank=True)),
                ('completed_courses', models.TextField(blank=True)),
                ('user_student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_major', models.CharField(blank=True, max_length=255, null=True)),
                ('user_year', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'graduation_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
