# Generated by Django 5.1.6 on 2025-09-13 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGraduationProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('earned_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='이수 학점')),
                ('required_credits', models.IntegerField(blank=True, null=True, verbose_name='필요 학점')),
                ('is_satisfied', models.BooleanField(default=False, verbose_name='충족 여부')),
                ('shortage_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='부족 학점')),
                ('category_level', models.IntegerField(default=0, verbose_name='카테고리 레벨')),
                ('parent_category_id', models.IntegerField(blank=True, null=True, verbose_name='부모 카테고리 ID')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.category')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_progress', to='data_manager.userprofile')),
            ],
            options={
                'verbose_name': '사용자 졸업요건 진행상황',
                'verbose_name_plural': '사용자 졸업요건 진행상황 목록',
                'db_table': 'user_graduation_progress',
                'indexes': [models.Index(fields=['user_profile', 'is_satisfied'], name='user_gradua_user_pr_782e68_idx'), models.Index(fields=['user_profile', 'shortage_credits'], name='user_gradua_user_pr_83077b_idx')],
                'unique_together': {('user_profile', 'category')},
            },
        ),
    ]
