# Generated by Django 5.1.6 on 2025-09-13 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_usergraduationprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingDistance',
            fields=[
                ('distance_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_building', models.CharField(help_text='건물 번호 또는 코드 (예: N1, S21)', max_length=10, verbose_name='출발 건물')),
                ('to_building', models.CharField(help_text='건물 번호 또는 코드 (예: N1, S21)', max_length=10, verbose_name='도착 건물')),
                ('walking_time', models.IntegerField(help_text='평균 도보 이동 시간', verbose_name='도보 시간(분)')),
                ('distance', models.IntegerField(help_text='건물 간 거리(미터)', verbose_name='거리(m)')),
            ],
            options={
                'verbose_name': '건물 간 거리',
                'verbose_name_plural': '건물 간 거리 목록',
                'db_table': 'building_distances',
                'indexes': [models.Index(fields=['from_building', 'to_building'], name='building_di_from_bu_6aaa71_idx')],
                'unique_together': {('from_building', 'to_building')},
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_instructors', models.JSONField(blank=True, default=list, help_text='선호하는 교수 이름 리스트', verbose_name='선호 교수 목록')),
                ('preferred_courses', models.JSONField(blank=True, default=list, help_text='선호하는 과목명 리스트', verbose_name='선호 과목 목록')),
                ('avoid_instructors', models.JSONField(blank=True, default=list, help_text='기피하는 교수 이름 리스트', verbose_name='기피 교수 목록')),
                ('avoid_courses', models.JSONField(blank=True, default=list, help_text='기피하는 과목명 리스트', verbose_name='기피 과목 목록')),
                ('max_walking_time', models.IntegerField(default=10, help_text='연속 수업 간 최대 허용 이동 시간', verbose_name='최대 이동 시간(분)')),
                ('prefer_compact_schedule', models.BooleanField(default=False, help_text='공강 시간을 최소화하는 시간표 선호 여부', verbose_name='밀집 시간표 선호')),
                ('prefer_morning_classes', models.BooleanField(default=False, help_text='오전 시간대 수업 선호 여부', verbose_name='오전 수업 선호')),
                ('prefer_afternoon_classes', models.BooleanField(default=False, help_text='오후 시간대 수업 선호 여부', verbose_name='오후 수업 선호')),
                ('min_break_time', models.IntegerField(default=10, help_text='연속 수업 사이 최소 휴식 시간', verbose_name='최소 휴식 시간(분)')),
                ('max_daily_classes', models.IntegerField(default=8, help_text='하루 최대 수업 시간', verbose_name='일일 최대 수업 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 선호도',
                'verbose_name_plural': '사용자 선호도 목록',
                'db_table': 'user_preferences',
            },
        ),
    ]
