# Generated by Django 5.1.6 on 2025-04-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_graduationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
                ('target_year', models.CharField(max_length=10)),
                ('grade_type', models.CharField(max_length=50)),
                ('foreign_course', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor_name', models.CharField(max_length=255)),
                ('lecture_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lecture_times', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lab_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lab_times', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pre_enrollment_count', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('enrolled_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Courses',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterModelTable(
            name='courseschedule',
            table='course_schedules',
        ),
    ]
