# Generated by Django 5.1.6 on 2025-09-24 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_coursereview_buildingdistance_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='created_at',
        ),
        migrations.AddField(
            model_name='userreview',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='익명 여부'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='수강 학기'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_manager.userprofile', verbose_name='작성자 프로필'),
        ),
    ]
