# Generated by Django 5.1.6 on 2025-04-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_courses_delete_course_alter_courseschedule_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduationrecord',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
