# Generated by Django 5.1.6 on 2025-04-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_alter_graduationrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduationrecord',
            options={'managed': False},
        ),
    ]
