# Generated by Django 5.1.6 on 2025-05-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0005_alter_graduationrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSumm',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_manager.courses', verbose_name='강의')),
                ('course_summarization', models.TextField(help_text='강의에 대한 간략한 설명을 입력하세요.', verbose_name='강의 요약')),
                ('group_activity', models.CharField(choices=[('Y', '있음'), ('N', '없음')], default='N', help_text="조별 과제가 있는 경우 'Y', 없는 경우 'N'을 선택하세요.", max_length=1, verbose_name='조별 과제 여부')),
            ],
            options={
                'verbose_name': '강의 요약 정보',
                'verbose_name_plural': '강의 요약 정보',
                'db_table': 'course_summ',
                'managed': False,
            },
        ),
    ]
