# Generated by Django 5.2.1 on 2025-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_coursesumm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, verbose_name='강의코드')),
                ('course_name', models.CharField(max_length=200, verbose_name='강의명')),
                ('instructor_name', models.CharField(max_length=100, verbose_name='교수명')),
                ('review_count', models.IntegerField(verbose_name='리뷰 개수')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='평균 평점')),
                ('dist_json', models.JSONField(verbose_name='분포 JSON')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 갱신일')),
            ],
            options={
                'verbose_name': '강의별 요약 통계',
                'verbose_name_plural': '강의별 요약 통계',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True, verbose_name='학생 ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='별점')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='리뷰 본문')),
                ('categories', models.JSONField(default=dict, verbose_name='카테고리 선택')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '개별 강의평',
                'verbose_name_plural': '개별 강의평',
                'managed': False,
            },
        ),
    ]
