# Generated by Django 5.2.1 on 2025-05-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0007_coursereviewsummary_userreview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursereviewsummary',
            table='course_review_summaries',
        ),
        migrations.AlterModelTable(
            name='userreview',
            table='user_review',
        ),
    ]
