# Generated by Django 5.2.1 on 2025-06-04 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0008_alter_coursereviewsummary_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('semester_year', models.IntegerField(default=2025)),
                ('semester_term', models.CharField(default='1학기', max_length=10)),
                ('total_credits', models.IntegerField(default=0)),
                ('major_credits', models.IntegerField(default=0)),
                ('elective_credits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saved_timetables',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedTimetableCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=50)),
                ('credits', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('instructor', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user_note', models.TextField(blank=True)),
                ('custom_color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'saved_timetable_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedTimetableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('time_slots', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'saved_timetable_schedules',
                'managed': False,
            },
        ),
    ]
