# config.yml
recipe: default.v1
assistant_id: timetable_assistant_v1

language: ko # 한국어로 변경

pipeline:
  # 기본 파이프라인
  - name: WhitespaceTokenizer
    intent_tokenization_flag: true
    intent_split_symbol: "+"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: CountVectorsFeaturizer
    analyzer: word
  - name: DIETClassifier
    epochs: 100
    entity_recognition: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100